[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wikiscraper"
version = "0.1.0"
requires-python = ">=3.11"
description = "WikiScraper project for Python course"
authors = [{ name = "Maciej Padarz" }]
readme = "README.md"
dependencies = [
  "beautifulsoup4>=4.12",
  "matplotlib>=3.8",
  "numpy>=1.26",
  "pandas>=2.1",
  "regex>=2024.0",
  "requests>=2.32",
  "seaborn>=0.13",
  "wordfreq>=3.1",
]

[project.optional-dependencies]
notebook = ["jupyter", "ipykernel"]
dev = ["black", "ruff", "pytest"]

[project.scripts]
wikiscraper = "wiki_scraper:main"
wiki_scraper_integration_test = "wiki_scraper_integration_test:main"


[tool.setuptools]
packages = { find = {} }
py-modules = ["wiki_scraper", "wiki_scraper_integration_test"]


[tool.black]
line-length = 88
target-version = ["py311"]

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = ["E", "W", "F", "I"]
ignore = ["E501"]

# importy
[tool.ruff.lint.isort]
known-first-party = ["wikiscraper"]
combine-as-imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]
