[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "wikiscraper"
version = "0.1.0"
requires-python = ">=3.11"
description = "WikiScraper project for Python course"
dependencies = [
    "requests",
    "beautifulsoup4",
    "pandas",
    "matplotlib",
    "wordfreq",
]

[tool.setuptools]
packages = { find = {} }


[tool.black]
line-length = 88
target-version = ["py311"]

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
# E/W = PEP8, F = realne błędy, I = porządek importów
select = ["E", "W", "F", "I"]

# dlugosc linii
ignore = ["E501"]

# importy
[tool.ruff.lint.isort]
known-first-party = ["wikiscraper"]
combine-as-imports = true

